# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Iy2WgB_ZfNhKyU6UfRdPjAyQzaNgg4q
"""

temp=float(input("Enter temperature in Celsius"))
F=(temp*9/5)+32
print("temperature in Fahrenheit is",F)