# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PXB0igobv_4S7lfjM5uapY95qoQlKt4A
"""

def check(number):
  if number%2==0:
    return "Even"
  else:
    return "odd"