# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iu2dUorxli0RnMGXYfUeFSkSlzn8VWjd
"""

year=int(input("Enter the year"))
if (year%4==0 and year%100!=0) or (year%400==0):
 print(year,"is a leap year")
else:
  print("Not a leap year")

