# -*- coding: utf-8 -*-
"""myphyton.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cli4qQwM5EoK27UDgWzQoKpv0tzX9v9s
"""

x = 10

if x > 5:
  print("x is greater than 5")  # This will raise an IndentationError
else:
    print("x is less than or equal to 5")
