# -*- coding: utf-8 -*-
"""Number of digits.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Iy2WgB_ZfNhKyU6UfRdPjAyQzaNgg4q
"""

def count_digits(n):
    count = 0
    if n == 0:
      return 1
    n = abs(n)
    while n > 0:
        n //= 10
        count += 1
    return count
print(count_digits(12345))

