# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Iy2WgB_ZfNhKyU6UfRdPjAyQzaNgg4q
"""

base = float(input("Enter the base number: "))
exponent = float(input("Enter the exponent number: "))
result = base ** exponent
print(f"{base} raised to the power of {exponent} is {result}")