# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PXB0igobv_4S7lfjM5uapY95qoQlKt4A
"""

def power(base,exponent):
  if exponent==0:
    return 1
  else:
    return base*power(base,exponent-1)
print(power(2,3))
print(power(3,2))