# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Iy2WgB_ZfNhKyU6UfRdPjAyQzaNgg4q
"""

user_input = input("Enter a string: ")
reversed_string = user_input[::-1]
print(f"The reversed string is: {reversed_string}")