# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iu2dUorxli0RnMGXYfUeFSkSlzn8VWjd
"""

i=int(input("Enter the number"))
sum=0
for i in range(1,i+1):
    sum=sum+i
print("The sum is",sum)

