# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Iy2WgB_ZfNhKyU6UfRdPjAyQzaNgg4q
"""

user_input = input("Enter a value: ")
if user_input.isdigit():
    number = int(user_input)
    print(f"The data type of the entered number is: {type(number)}")
else:
    try:
        number = float(user_input)
        print(f"The data type of the entered number is: {type(number)}")
    except ValueError:
              print(f"The data type of the entered value is: {type(user_input)}")